# "Enabled" must be true for the plugin to function properly
# Make sure you have your default state properly set up below before enabling!
enabled: true

# default materials that are actually in the world
default-leaf-material: OAK_LEAVES
default-log-material: OAK_LOG
default-stripped-log-material: STRIPPED_OAK_LOG

leaves:
  "test_leaves":
    world-persistence: false
    leaf-material: OAK_LEAVES
    material: PAPER
    model-data: 1
    name: "&Test Leaves"
    lore:
      - "&aLine 1"
      - "&bLine 2"
    state-id: 1
    sapling:
      material: OAK_SAPLING
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
    leaf-drop-replacement:
      material: OAK_LEAVES
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"

logs:
  test_log:
    log-material: OAK_LOG
    stripped-log-material: STRIPPED_OAK_LOG
    material: PAPER
    model-data: 2
    name: "&5Test Log"
    lore:
      - "&aLine 1"
    instrument: BANJO
    note: 2
    stripped-instrument: BANJO
    stripped-note: 3
