# "Enabled" must be true for the plugin to function properly
# Make sure you have your default state properly set up below before enabling!
enabled: false
# THE BELOW STATES ARE THE DEFAULT STATES FOR LEAVES GENERATED IN THE WORLD
# 13, 27, 41, 55, 69, 83, 97, 111, 125

# default materials that are actually in the world
default-leaf-material: OAK_LEAVES
default-log-material: OAK_LOG
default-stripped-log-material: STRIPPED_OAK_LOG

leaves:
  "glowstone_leaves":
    leaf-material: OAK_LEAVES
    material: PAPER
    model-data: 1
    name: "&5Glowstone Leaves"
    lore:
      - "&aLine 1"
      - "&bLine 2"
    state-id: 1
    sapling:
      hook-id: test-sapling
      material: OAK_SAPLING
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
    leaf-drop-replacement:
      hook-id: test
      material: OAK_LEAVES
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"

logs:
  "netherite_log":
    log-material: OAK_LOG
    stripped-log-material: STRIPPED_OAK_LOG
    material: NETHERITE_BLOCK
    model-data: 2
    name: "&5Netherite Block"
    lore:
        - "&aLine 1"
    instrument: BANJO
    note: 2
#items:
#  "palm_leaves":
#    leaf-material: OAK_LEAVES
#    material: PAPER