# "Enabled" must be true for the plugin to function properly
# Make sure you have your default state properly set up below before enabling!
enabled: false
# Default state for the normal leaf type
default-state:
  persistent: true
  distance: 7
  actually-persistent: true
items:
  "palm_leaves":
    leaf-material: OAK_LEAVES
    material: PAPER
    model-data: 1 # If using Oraxen/IA, you can ignore this option. Get the leaf item from /o inv or /ia.
    # Blockstate Data
    distance: 6
    persistent: true
    # Will this leaf decay, or will it be persistent?
    actually-persistent: false
    # The item that replaces the normal sapling drop. For example if you have an item that is textured to look like a sapling that matches the tree this leaf goes with
    sapling:
      hook-id: test-sapling
      material: OAK_SAPLING
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
    # The item that should replace the leaf normally dropped from shears, for example an Oraxen / ItemsAdder leaf item that players use to place this leaf
    leaf-drop-replacement:
      hook-id: test
      material: OAK_LEAVES
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
  "palm_leaves_persistent":
    leaf-material: OAK_LEAVES
    material: PAPER
    model-data: 1
    persistent: true
    actually-persistent: true
    distance: 6
    sapling:
      hook-id: test-sapling
      material: OAK_SAPLING
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
    leaf-drop-replacement:
      hook-id: test
      material: OAK_LEAVES
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
# In this section, you can define custom logs. When a leaf is placed on a custom log, it will not decay. 
logs:
  noteblocks:
    # Name of log
    palm_log:
      # Blockstate data for the log
      instrument: FLUTE
      note: 21