# "Enabled" must be true for the plugin to function properly
# Make sure you have your default state properly set up below before enabling!
enabled: true

# default materials that are actually in the world
default-leaf-material: OAK_LEAVES
default-log-material: OAK_LOG
default-stripped-log-material: STRIPPED_OAK_LOG

# If a player places a leaf and it has a distance >= 7 and this setting is true,
# it will still be persistent even if world-persistence is set to false
only-follow-world-persistence-if-connected-to-log: true

use-world-whitelist: true
whitelisted-worlds:
  - "world"

leaves:
  "test_leaves":
    world-persistence: false
    leaf-material: OAK_LEAVES
    material: PAPER
    model-data: 1
    name: "&Test Leaves"
    lore:
      - "&aLine 1"
      - "&bLine 2"
    state-id: 1
    sapling: test_sapling
    leaf-drop-replacement: test_leaves
    model-path: "blocks/leaves/test_leaves"

logs:
  test_log:
    log-material: OAK_LOG
    stripped-log-material: STRIPPED_OAK_LOG
    material: PAPER
    model-data: 2
    name: "&5Test Log"
    lore:
      - "&aLine 1"
    instrument: BANJO
    note: 2
    stripped-instrument: BANJO
    stripped-note: 3

saplings:
  test_sapling:
    sapling-material: OAK_SAPLING
    material: PAPER
    model-data: 3
    name: "&6Test Sapling"
    lore:
      - "&aLine 1"
    stage: 1
    schematic-files:
      - "test.schem"
      - "test2.schem"
    random-paste-rotation: true
    model-path: "blocks/saplings/test_sapling"
    allowed-soil-blocks:
      materials:
        - STONE
      tags:
        - dirt
      hook-block-ids:
        - amethyst_block

cave-vines:
  test_cave_vine:
    material: paper
    with-glow-berry-id: test_cave_vine_berries
    model-data: 5
    name: "&6Test Cave Vine"
    lore:
      - "&aLine 1"
    state-id: 2

sugar-cane:
  test_sugar_cane:
    material: paper
    model-data: 6
    name: "&6Test Sugar Cane"
    lore:
      - "&aLine 1"
    state-id: 1
    stack-limit: 6

kelp:
  test_kelp:
    material: paper
    model-data: 6
    name: "&6Test Kelp"
    lore:
      - "&aLine 1"
    state-id: 1

twisting-vines:
  test_twisting_vine:
    material: paper
    model-data: 6
    name: "&6Test Twisting Vine"
    lore:
      - "&aLine 1"
    state-id: 1

weeping-vines:
  test_weeping_vine:
    material: paper
    model-data: 6
    name: "&6Test Weeping Vine"
    lore:
      - "&aLine 1"
    state-id: 1