name: HMCLeaves
version: "1.1.0-beta"
main: io.github.fisher2911.hmcleaves.HMCLeaves
softdepend: [ Oraxen, ItemsAdder ]
api-version: 1.16
loadbefore:
  - RoseLoot
permissions:
  hmcleaves.command.item:
    description: "Allows the player to use the /leaf command"
    default: op
commands:
  "hmcleaves":
    description: "Allows the player to use the /leaf command"
    permission: hmcleaves.command.item