name: HMCLeaves
version: "2.4.1-beta"
main: io.github.fisher2911.hmcleaves.HMCLeaves
softdepend: [ Oraxen, ItemsAdder, WorldEdit, FastAsyncWorldEdit, ProtocolLib, ProtocolSupport, ViaVersion, ViaBackwards, ViaRewind, Geyser-Spigot ]
api-version: 1.18
loadbefore:
  - RoseLoot
permissions:
  hmcleaves.command.item:
    description: "Allows the player to use the /hmcleaves give command"
    default: op
  hmcleaves.command.debugtool:
    description: "Allows the player to use the /hmcleaves debugtool command"
    default: op
  hmcleaves.command.reload:
    description: "Allows the player to use the /hmcleaves reload command"
    default: op
  hmcleaves.command.transformschem:
    description: "Allows the player to use the /hmcleaves transformschem command"
    default: op
commands:
  "hmcleaves":
    description: "Allows the player to use the /leaf command"
    permission: hmcleaves.command.item