database-settings:
  type: SQLite

# adds debug messages
debug: false

custom-mining-speed-for-default-logs: true

whitelisted-worlds:
  - "world"
use-world-whitelist: false

# if the texture files should be transferred to Oraxen
use-texture-hook: true

blocks:
  # block id
  aspen_sapling:
    type: sapling
    world-material: oak_sapling
    visual-material: oak_sapling
    texture-pack:
      model-path: "aspen_sapling"
    schematic:
      files:
        - "aspen_tree_1.schem"
        - "aspen_tree_2.schem"
      random-rotation: true
    properties:
      stage: 1
    item:
      material: PAPER
      name: "<red>Aspen Sapling"
      model-data: 1

  aspen_log:
    type: log
    world-material: oak_log
    visual-material: note_block
    generate-directions: true
    texture-pack:
      model-path: "aspen_log"
      parent: "block/cube_column"
      textures:
        side: "hmcleaves/aspen_log"
        end: "hmcleaves/aspen_log_top"
    # allows directional blocks to be generated,
    # the below values are required for logs
    block-family:
      AXIS_X: "aspen_log_x"
      AXIS_Y: "aspen_log_y"
      AXIS_Z: "aspen_log_z"
      STRIPPED: "stripped_aspen_log"
    properties:
      instrument: flute
      note: 5
    item:
      material: PAPER
      name: "<red>Aspen Log"
      model-data: 1
    block-break-modifier:
      hardness: 2.0
      requires-tool: false
      tool-types:
        - AXE
    hit-sound:
      name: "minecraft:block.bell.use"
      category: "AMBIENT"
      volume: 1.0
      pitch: 1.0
    step-sound:
      name: "minecraft:block.bell.use"
      category: "AMBIENT"
      volume: 1.0
      pitch: 1.0
    place-sound:
      name: "minecraft:block.bell.use"
      category: "AMBIENT"
      volume: 1.0
      pitch: 1.0
    break-sound:
      name: "minecraft:block.bell.use"
      category: "AMBIENT"
      volume: 1.0
      pitch: 1.0

  stripped_aspen_log:
    type: stripped_log
    world-material: stripped_oak_log
    visual-material: note_block
    texture-pack:
      model-path: "stripped_aspen_log"
    # allows directional blocks to be generated,
    # the below values are required for stripped logs
    block-family:
      AXIS_X: "stripped_aspen_log"
      AXIS_Y: "stripped_aspen_log"
      AXIS_Z: "stripped_aspen_log"
      NOT_STRIPPED: "aspen_log"
    generate-directions: false
    properties:
      instrument: flute
      note: 9
    item:
      material: PAPER
      name: "<red>Stripped Aspen Log"
      model-data: 1
    block-break-modifier:
      hardness: 2.0
      requires-tool: false
      tool-types:
        - AXE

  sugar_cane:
    type: sugar_cane
    world-material: sugar_cane
    visual-material: sugar_cane
    properties:
      age: 2
    item:
      material: PAPER
      name: "<green>Sugar Cane"
      model-data: 4
    place-conditions:
      id: sugarcane
  fake_grass:
    type: server_side_block
    world-material: grass_block
    visual-material: note_block
    properties:
      instrument: flute
      note: 2
    item:
      material: PAPER
      name: "<green>Fake Grass Block"
      model-data: 4
    block-break-modifier:
      hardness: 5
      tool-types:
        - shovel
  custom_cave_vines_plant:
    item:
      material: PAPER
      name: "<blue>Custom Cave Vines Plant"
    type: cave_vines_plant
    world-material: cave_vines_plant
    visual-material: cave_vines
    block-family:
      NOT_PLANT: "custom_cave_vines"
    connects-to:
      - custom_cave_vines
    properties:
      age: 8
    drops:
      type: mapped_replacement
      GLOW_BERRIES:
        material: PAPER
        name: <aqua>Paper Glow Berries
        model-data: 5
  custom_cave_vines:
    item:
      material: PAPER
      name: "<blue>Custom Cave Vines"
    type: cave_vines
    visual-material: cave_vines
    world-material: cave_vines
    block-family:
      PLANT: "custom_cave_vines_plant"
    connects-to:
      - custom_cave_vines_plant
    properties:
      age: 9
    drops:
      type: mapped_replacement
      GLOW_BERRIES:
        material: PAPER
        name: <aqua>Paper Glow Berries
        model-data: 5
  string_sugar_cane:
    type: server_side_block
    world-material: tripwire
    visual-material: sugar_cane
    properties:
      age: 2
    place-conditions:
      1:
        DOWN:
          materials:
            - DIAMOND_BLOCK
          ids:
            - string_sugar_cane
    item:
      material: PAPER
      name: "<green>String Sugar Cane"
      model-data: 4