database-settings:
  type: SQLite

# adds debug messages
debug: false

custom-mining-speed-for-default-logs: true

whitelisted-worlds:
  - "world"
use-world-whitelist: false

# if the texture files should be transferred to Oraxen
use-texture-hook: true

blocks:
  # block id
  palm_leaves:
    # item that is used in the inventory
    item:
      material: PAPER
      name: "<blue>Palm Leaves"
    # type of block
    type: leaves
    # what block is actually placed in the world
    world-material: oak_leaves
    # what block is sent to the player
    visual-material: oak_leaves
    # model path used for texture packs
    model-path: "palm_leaves"
    # properties that are displayed to the player
    properties:
      distance: 7
      persistent: false
  aspen_leaves:
    # below is an example of how to use an Oraxen item to place the block
#    item-id: some-oraxen-item
    item:
      material: PAPER
      name: "<blue>Aspen Leaves"
    type: leaves
    world-material: oak_leaves
    visual-material: oak_leaves
    model-path: "aspen_leaves"
    properties:
      distance: 6
      persistent: false
  pine_leaves:
    item:
      material: PAPER
      name: "<blue>Pine Leaves"
    type: leaves
    world-material: oak_leaves
    visual-material: oak_leaves
    model-path: "pine_leaves"
    properties:
      distance: 5
      persistent: false

  aspen_log:
    type: log
    world-material: oak_log
    visual-material: note_block
    model-path: "aspen_log"
    # allows directional blocks to be generated,
    # the below values are required for logs
    block-family:
      AXIS_X: "aspen_log_x"
      AXIS_Y: "aspen_log_y"
      AXIS_Z: "aspen_log_z"
      STRIPPED: "stripped_aspen_log"
    properties:
      instrument: flute
      note: 5
    item:
      material: PAPER
      name: "<red>Aspen Log"
      model-data: 1

  stripped_aspen_log:
    type: stripped_log
    world-material: stripped_oak_log
    visual-material: note_block
    model-path: "stripped_aspen_log"
    # allows directional blocks to be generated,
    # the below values are required for stripped logs
    block-family:
      AXIS_X: "aspen_log_x"
      AXIS_Y: "aspen_log_y"
      AXIS_Z: "aspen_log_z"
      NOT_STRIPPED: "aspen_log"
    properties:
      instrument: flute
      note: 9
    item:
      material: PAPER
      name: "<red>Stripped Aspen Log"
      model-data: 1

  sugar_cane:
    type: sugar_cane
    world-material: sugar_cane
    visual-material: sugar_cane
    properties:
      age: 2
    item:
      material: PAPER
      name: "<green>Sugar Cane"
      model-data: 4
    place-conditions:
      id: sugarcane
  fake_grass:
    type: server_side_block
    world-material: grass_block
    visual-material: note_block
    properties:
      instrument: flute
      note: 2
    item:
      material: PAPER
      name: "<green>Fake Grass Block"
      model-data: 4
    block-break-modifier:
      hardness: 5
      tool-types:
        - shovel
  custom_cave_vines_plant:
    item:
      material: PAPER
      name: "<blue>Custom Cave Vines Plant"
    type: cave_vines_plant
    world-material: cave_vines_plant
    visual-material: cave_vines
    block-family:
      NOT_PLANT: "custom_cave_vines"
    connects-to:
      - custom_cave_vines
    properties:
      age: 8
    drops:
      type: mapped_replacement
      GLOW_BERRIES:
        material: PAPER
        name: <aqua>Paper Glow Berries
        model-data: 5
  custom_cave_vines:
    item:
      material: PAPER
      name: "<blue>Custom Cave Vines"
    type: cave_vines
    visual-material: cave_vines
    world-material: cave_vines
    block-family:
      PLANT: "custom_cave_vines_plant"
    connects-to:
      - custom_cave_vines_plant
    properties:
      age: 9
    drops:
      type: mapped_replacement
      GLOW_BERRIES:
        material: PAPER
        name: <aqua>Paper Glow Berries
        model-data: 5
  string_sugar_cane:
    type: server_side_block
    world-material: tripwire
    visual-material: sugar_cane
    properties:
      age: 2
    place-conditions:
      1:
        DOWN:
          materials:
            - DIAMOND_BLOCK
          ids:
            - string_sugar_cane
    item:
      material: PAPER
      name: "<green>String Sugar Cane"
      model-data: 4