database-settings:
  type: SQLite

debug: false

custom-mining-speed-for-default-logs: true

blocks:
  aspen_leaves:
    type: leaves
    world-material: oak_leaves
    visual-material: oak_leaves
    properties:
      distance: 3
      persistent: true
  aspen_log:
    type: log
    world-material: oak_log
    visual-material: note_block
    properties:
      instrument: flute
      note: 5
    item:
      material: PAPER
      name: "<red>Aspen Log"
      model-data: 1
  aspen_log_x:
    type: log
    world-material: oak_log
    visual-material: note_block
    properties:
      instrument: flute
      note: 6
    item:
      material: PAPER
      name: "<red>Aspen Log (x)"
      model-data: 2
  aspen_log_y:
    type: log
    world-material: oak_log
    visual-material: note_block
    properties:
      instrument: flute
      note: 7
    item:
      material: PAPER
      name: "<red>Aspen Log (y)"
      model-data: 3
  aspen_log_z:
    type: log
    world-material: oak_log
    visual-material: note_block
    properties:
      instrument: flute
      note: 8
    item:
      material: PAPER
      name: "<red>Aspen Log (z)"
      model-data: 4
  sugar_cane:
    type: sugar_cane
    world-material: sugar_cane
    visual-material: sugar_cane
    properties:
      age: 2
    item:
      material: PAPER
      name: "<green>Sugar Cane"
      model-data: 4
    place-conditions:
      id: sugarcane
  fake_grass:
    type: server_side_block
    world-material: grass_block
    visual-material: note_block
    properties:
      instrument: flute
      note: 2
    item:
      material: PAPER
      name: "<green>Fake Grass Block"
      model-data: 4
    block-break-modifier:
      hardness: 5
      tool-types:
        - shovel
  custom_cave_vines_plant:
    type: cave_vines_plant
    world-material: cave_vines_plant
    visual-material: cave_vines
    connects-to:
      - custom_cave_vines
    properties:
      age: 8
    drops:
      type: mapped_replacement
      GLOW_BERRIES:
        material: PAPER
        name: <aqua>Paper Glow Berries
        model-data: 5
  custom_cave_vines:
    type: cave_vines
    visual-material: cave_vines
    world-material: cave_vines
    connects-to:
      - custom_cave_vines_plant
    properties:
      age: 9
    drops:
      type: mapped_replacement
      GLOW_BERRIES:
        material: PAPER
        name: <aqua>Paper Glow Berries
        model-data: 5
  string_sugar_cane:
    type: server_side_block
    world-material: tripwire
    visual-material: sugar_cane
    properties:
      age: 2
    place-conditions:
      1:
        DOWN:
          materials:
            - DIAMOND_BLOCK
          ids:
            - string_sugar_cane
    item:
      material: PAPER
      name: "<green>String Sugar Cane"
      model-data: 4